version: '3'
services:
   influxdb:
        image:  influxdb:1.5.4
        ports:
          - "8086:8086"
   telegraf:
        image: telegraf:1.11.5
        volumes:
          - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
        ports:
          - "8094:8094"
   grafana:
        image: grafana/grafana:6.6.2
        ports:
          - "3000:3000"
        volumes:
          - ./grafana/dashboards:/var/lib/grafana/dashboards/
          - ./grafana/provisioning/:/etc/grafana/provisioning/
